/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fram;

/**
 *
 * @author Info Pratique
 */
import java.lang.String;
import java.util.ArrayList;
public class convertor extends javax.swing.JFrame {

    /**
     * Creates new form convertor
     */
    public convertor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SQLtext = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JasonResulte = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SQLtext.setColumns(20);
        SQLtext.setRows(5);
        jScrollPane1.setViewportView(SQLtext);

        jButton1.setText("Execute");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JasonResulte.setColumns(20);
        JasonResulte.setRows(5);
        jScrollPane2.setViewportView(JasonResulte);

        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("table plus utilisé");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 127, Short.MAX_VALUE))
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char type = SQLtext.getText().toCharArray()[0];
        Requet REQUETS = new Requet(type);
        if(type=='I'){   
            Insert ins=new Insert(SQLtext.getText()); 
            JasonResulte.setText(ins.getJsoneCode());
        }
        if(type=='C'){
            String[][] req = separate(SQLtext.getText());
            Create tab;
            for (int i = 0;i < req.length;i++){
                if(Requet.requetType(req[i][1])=="C"){
                    tab = new Create(req[i][1],i+1);
                    REQUETS.createTable.add(tab);
                }    
            }
            for(int i=0;i<REQUETS.createTable.size();i++){
                if(REQUETS.createTable.get(i).getTableName().equals(jTextField1.getText())){
                    REQUETS.createTable.get(i).setPrinciple(true);
                    REQUETS.createTable.get(i).setPreority(0);
                }
            }
            REQUETS.setPrincipleTable();
            String[] Ptables=jTextField1.getText().split("\\ ");
            for(int i=0;i<REQUETS.createTable.size();i++){
                for(int j=0;j<Ptables.length;j++){
                    if(REQUETS.createTable.get(i).getTableName().equals(Ptables[j])){
                        REQUETS.createTable.get(i).setPrinciple(true);
                    }
                }
            }
            REQUETS.setExternalKeys();
            REQUETS.jsoncode();
            String result=REQUETS.getJsoncode();
            JasonResulte.setText(result);
            System.out.println("8888888888888888888888888888888888");
            for(int i =0;i<REQUETS.createTable.size();i++){
                REQUETS.createTable.get(i).printor();
            }
            System.out.println("8888888888888888888888888888888888");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1MouseClicked
    public String removevoid(String req){
        String reqt[]=req.split("\\r?\\n");
        String reqs = null;
        reqs=reqt[1];
        
        for(int i=2;i<reqt.length;i++){
            reqs=reqs+"\n"+reqt[i];
        }
        return reqs;
    }
    public String[][] getreqtype(String[] req){
        String[][] reqt = new String[req.length][2];
        String[] text=null;
        for (int j=1;j<req.length;j++){
           req[j]=removevoid(req[j]);
        }
        for (int i=0;i<req.length;i++){
            reqt[i][1]=req[i];
            text=req[i].split("\\ ");
            reqt[i][0]=text[0]; 
            
        }
        return reqt;
    }
                
    public String[][] separate(String req){
        //ArrayList requets=new ArrayList();
        String requets[] = req.split("\\;");
        System.out.println(" la taiile de la table est");
        System.out.println(requets.length);
        return getreqtype(requets);     
    } 
    
    public boolean isValid(String[] Request){
        switch (Request[0]){
            case "SELECT":
                if (Request[1].equals("FROM")){
                    return false;
                }
                for (int i=2;i < Request.length-1;i++){
                    if (Request[i].equals("FROM")){
                        //System.out.print(Request[i]);
                        return true;
                    }
                }
                return false;
            case "CREATE":
                return true;
            default:
                return false;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea JasonResulte;
    private javax.swing.JTextArea SQLtext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private String tostring(String[] RequetSQL) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
